### ISSUE TITLE
test `test_cluster_id_isolation` is flaky

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1313]
As observed in CI.
```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/quickwit_cluster-16bbb7af005f17c2)

running 6 tests
thread 'cluster::tests::test_cluster_id_isolation' panicked at 'called `Result::unwrap()` on an `Err` value: deadline has elapsed', quickwit-cluster/src/cluster.rs:439:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
   4: quickwit_cluster::cluster::tests::test_cluster_id_isolation::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   8: tokio::coop::with_budget::{{closure}}
   9: std::thread::local::LocalKey<T>::try_with
  10: std::thread::local::LocalKey<T>::with
  11: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
  12: tokio::runtime::basic_scheduler::Context::enter
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
  14: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
  16: tokio::runtime::basic_scheduler::CoreGuard::enter
  17: tokio::runtime::basic_scheduler::CoreGuard::block_on
  18: tokio::runtime::basic_scheduler::BasicScheduler::block_on
  19: tokio::runtime::Runtime::block_on
  20: quickwit_cluster::cluster::tests::test_cluster_id_isolation
  21: quickwit_cluster::cluster::tests::test_cluster_id_isolation::{{closure}}
  22: core::ops::function::FnOnce::call_once
  23: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
F...member=Member { node_unique_id: "674baf6d-3746-4fda-92bf-0baf764595a6", generation: 1, gossip_public_address: 127.0.0.1:12[345](https://github.com/quickwit-oss/quickwit/runs/6088336394?check_suite_focus=true#step:7:345), is_self: true }
proto_member=Member { id: "674baf6d-3746-4fda-92bf-0baf764595a6/1", listen_address: "127.0.0.1:12345", is_self: true, generation: 1 }
expected=Member { id: "674baf6d-3746-4fda-92bf-0baf764595a6/1", listen_address: "127.0.0.1:12345", is_self: true, generation: 1 }
..
failures:

failures:
    cluster::tests::test_cluster_id_isolation
```

**Comment by PSeitz** [comment]
Still flaky 

```
thread 'cluster::tests::test_cluster_id_isolation' panicked at 'called `Result::unwrap()` on an `Err` value: deadline has elapsed', quickwit-cluster/src/cluster.rs:440:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
   4: quickwit_cluster::cluster::tests::test_cluster_id_isolation::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   8: tokio::coop::with_budget::{{closure}}
   9: std::thread::local::LocalKey<T>::try_with
  10: std::thread::local::LocalKey<T>::with
  11: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
  12: tokio::runtime::basic_scheduler::Context::enter
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
  14: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
  16: tokio::runtime::basic_scheduler::CoreGuard::enter
  17: tokio::runtime::basic_scheduler::CoreGuard::block_on
  18: tokio::runtime::basic_scheduler::BasicScheduler::block_on
  19: tokio::runtime::Runtime::block_on
  20: quickwit_cluster::cluster::tests::test_cluster_id_isolation
  21: quickwit_cluster::cluster::tests::test_cluster_id_isolation::{{closure}}
  22: core::ops::function::FnOnce::call_once
  23: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
..F.member=Member { node_unique_id: "02f873f8-cad3-43f9-8edd-97c25139d67a", generation: 1, gossip_public_address: 127.0.0.1:12345, is_self: true }
proto_member=Member { id: "02f873f8-cad3-43f9-8edd-97c25139d67a/1", listen_address: "127.0.0.1:12345", is_self: true, generation: 1 }
expected=Member { id: "02f873f8-cad3-43f9-8edd-97c25139d67a/1", listen_address: "127.0.0.1:12345", is_self: true, generation: 1 }
..
failures:

failures:
    cluster::tests::test_cluster_id_isolation

```
