### ISSUE TITLE
Aggregation error: StorageDirectory only supports async reads

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#3225]
This is a regression, it worked before
```
➜  quickwit-indices curl -X POST -w '\nTotal: %{time_total}s\n' -H "Content-Type: application/json" -d @airmail_agg_request.json  http://127.0.0.1:7280/api/v1/airmail/search
{"message":"Internal error: `(Internal error: `An IO error occurred: 'Unsupported operation. StorageDirectory only supports async reads: \"ee3408a0c7874280a2caad0d1ac97bc8.fast\"'`., split_id: 01GYW5TWR8PBKA
AGNJ9STNJNW3), (Internal error: `An IO error occurred: 'Unsupported operation. StorageDirectory only supports async reads: \"31527bafae3640af93dca5612f88c451.fast\"'`., split_id: 01GYW5WQC6M7JX8M5TF8XP8VBN),
 (Internal error: `An IO error occurred: 'Unsupported operation. StorageDirectory only supports async reads: \"03a7e274bbbd4b74ae61a1c69aac548f.fast\"'`., split_id: 01GYW5YJ0GW8K831KKKH28G1KC)`."}
Total: 0.011275s
```

```json
{
  "query": "*",
  "max_hits": 0,
  "aggs":
    {"metrics":{"date_histogram":{"field":"_ts","fixed_interval":"15m"},"aggs":{"response":{"percentiles": {"field": "response"}}}}}
}
```

**Comment by fulmicoton** [comment]
I assume you know that, but this means the fastfield was not warmed up, meaning the collector did not list correctly all of the stuff to warmup or that there is a bug in the wramup logic.

**Comment by PSeitz** [comment]
So here are the steps that caused this.
- Ingest data via local fs
- Cancel the ingest

The hotcache directory was in an invalid state then and did not contain the data required to open an Index.
It's fixed after re-ingesting the data.

```
thread 'tokio-runtime-worker' panicked at 'waaaa', quickwit-directories/src/storage_directory.rs:58:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: <quickwit_directories::storage_directory::StorageDirectoryFileHandle as tantivy_common::file_slice::FileHandle>::read_bytes
   3: <quickwit_directories::caching_directory::CachingFileHandle as tantivy_common::file_slice::FileHandle>::read_bytes
   4: tantivy_common::file_slice::FileSlice::read_bytes_slice
   5: <quickwit_directories::hot_directory::FileSliceWithCache as tantivy_common::file_slice::FileHandle>::read_bytes
   6: tantivy_common::file_slice::FileSlice::read_bytes
   7: tantivy_sstable::dictionary::Dictionary<TSSTable>::open
   8: tantivy_columnar::columnar::reader::ColumnarReader::open_inner
   9: tantivy_columnar::columnar::reader::ColumnarReader::open
  10: tantivy::fastfield::readers::FastFieldReaders::open
  11: tantivy::core::segment_reader::SegmentReader::open_with_custom_alive_set
  12: tantivy::core::segment_reader::SegmentReader::open
  13: core::ops::function::FnMut::call_mut
  14: core::iter::adapters::map::map_try_fold::{{closure}}
  15: core::iter::traits::iterator::Iterator::try_fold
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  17: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
  18: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  21: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  22: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
  23: core::iter::adapters::try_process
  24: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
  25: core::iter::traits::iterator::Iterator::collect
  26: tantivy::reader::InnerIndexReader::open_segment_readers
  27: tantivy::reader::InnerIndexReader::create_searcher
  28: tantivy::reader::InnerIndexReader::new
  29: tantivy::reader::IndexReaderBuilder::try_into
  30: quickwit_search::leaf::leaf_search_single_split::{{closure}}::{{closure}}
  31: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  32: quickwit_search::leaf::leaf_search_single_split::{{closure}}
  33: quickwit_search::leaf::leaf_search::{{closure}}::{{closure}}::{{closure}}
```
