### ISSUE TITLE
flaky quickwit-integration-tests test

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/quickwit#4213]
```
 failures:
    tests::index_tests::test_ingest_v2_happy_path

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 0.17s


--- TRY 2 STDERR:        quickwit-integration-tests tests::index_tests::test_ingest_v2_happy_path ---
thread 'tests::index_tests::test_ingest_v2_happy_path' panicked at 'called `Result::unwrap()` on an `Err` value: Api(ApiError { message: Some("index `test_index` not found"), code: 404 })', quickwit-integration-tests/src/tests/index_tests.rs:309:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
   4: quickwit_integration_tests::tests::index_tests::test_ingest_v2_happy_path::{{closure}}
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
   9: tokio::runtime::scheduler::current_thread::Context::enter
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
  11: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::set_scheduler::{{closure}}
  14: std::thread::local::LocalKey<T>::try_with
  15: std::thread::local::LocalKey<T>::with
  16: tokio::runtime::context::set_scheduler
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  20: tokio::runtime::context::runtime::enter_runtime
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  22: tokio::runtime::runtime::Runtime::block_on
  23: quickwit_integration_tests::tests::index_tests::test_ingest_v2_happy_path
  24: quickwit_integration_tests::tests::index_tests::test_ingest_v2_happy_path::{{closure}}
  25: core::ops::function::FnOnce::call_once
  26: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fulmicoton** [comment]
https://github.com/quickwit-oss/quickwit/actions/runs/9213784204/job/25348457045

**Comment by fulmicoton** [comment]
(I managed to reproduce consistently by adding a time sleep before adding nodes to the ingester pool. and confirmed the PR fixed this)
