### ISSUE TITLE
Invoking search on quickwit lambda

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4381]
I got the following error on the first call of `make invoke-hdfs-searcher-term`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/cdk/cli.py", line 221, in invoke_hdfs_searcher
    return _invoke_searcher(
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/cdk/cli.py", line 216, in _invoke_searcher
    download_logs_to_file(lambda_result.request_id(), function_name, invoke_start)
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/cdk/cli.py", line 275, in download_logs_to_file
    for log in get_logs(
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/cdk/cli.py", line 242, in get_logs
    for page in paginator.paginate(
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/.venv/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/.venv/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/.venv/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/fmassot/quickwit/repos/quickwit/distribution/lambda/.venv/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the FilterLogEvents operation: The specified log group does not exist.
make: *** [Makefile:80: invoke-hdfs-searcher-term] Error 1

```

**Comment by rdettai** [comment]
For some reason, the log group is not visible on the first call to the Lambda. This is surprising as it is supposed to be created by CDK. In https://github.com/quickwit-oss/quickwit/pull/4453 I made the error message a bit less scary by removing the stack trace 😄
